# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy: 
          matrix: 
            machines: [1, 2, 3]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Install front-end packages
              working-directory: ./front
              run: npm install
              
            - name: Start front-end
              working-directory: ./front
              run: npm run dev
              continue-on-error: true
              
            - name: Install back-end packages
              working-directory: ./back
              run: npm install
              
            - name: Start back-end
              working-directory: ./back
              run: npm run start
              continue-on-error: true
              
            - name: Start ngrok front
              working-directory: ./front
              run: npm run ngrok
              
              continue-on-error: true
            - name: Start ngrok back
              working-directory: ./back
              run: npm run ngrok
              
              continue-on-error: true
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  record: true
                  parallel: true
                  group: Actions example
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
