name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install NPM Packages
              uses: npm install
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: firefox
