# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch

    push: 
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                containers: [1, 2, 3]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Login
              uses: cypress-io/github-action@v2
              with:
                  working-directory: front
                  config-file: cypress.json
                  record: true
                  parallel: true
                  group: "Auth"
                  spec: "cypress/integration/auth/login_spec.js"
                  browser: firefox
            - name: Register
              uses: cypress-io/github-action@v2
              with:
                  working-directory: front
                  config-file: cypress.json
                  record: true
                  parallel: true
                  group: "Auth"
                  spec: "cypress/integration/auth/register_spec.js"
                  browser: firefox
            - name: Posts/Comments/Likes
              uses: cypress-io/github-action@v2
              with:
                  working-directory: front
                  config-file: cypress.json
                  record: true
                  parallel: true
                  group: "Posts/Comments"
                  spec: |
                      cypress/integration/posts_headless/*
                      cypress/integration/comments_headless/*
                      cypress/integration/likes_headless/*
                  browser: firefox
            - name: Friends/Messages
              uses: cypress-io/github-action@v2
              with:
                  working-directory: front
                  config-file: cypress.json
                  record: true
                  parallel: true
                  group: "Friends/Messages"
                  spec: cypress/integration/friends_headless/*
                  browser: firefox

              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
